export const primaryColor = '#C3073f'
export const primaryDarkColor = '#1A1A1D'
export const succesColor = '#1F97F6'
export const infoColor = '#1F97F6'
export const errorColor = '#f2af29'
export const warningColor = '#f2af29'
